######################################################################
# Automatically generated by qmake (3.0) Wed Feb 15 14:11:12 2017
######################################################################

TEMPLATE     = app
CONFIG      += console
TARGET       = emul
INCLUDEPATH += .
QT          += serialport

# Input
SOURCES     += emul.cpp 
